//! Multi-project TUI state: typed tab identity, ordered tab collection,
//! per-tab project/workspace/session summaries, and bounded project
//! catalog cache.
//!
//! This module is the **frontend-local** state seam required by the
//! Multi-Project TUI roadmap (milestone 1). It does **not** introduce
//! any new project discovery, catalog storage, or session authority.
//! All durable project / workspace / session identity still comes from
//! the daemon through `CoreClient`; the values cached here are
//! summaries used for picker rendering and active-tab accessors.
//!
//! Invariants enforced by this module:
//!
//! * Tab IDs are opaque, frontend-local UUID strings. They are NEVER
//!   reused as daemon project IDs or session IDs.
//! * The catalog cache only contains `ProjectSummaryDto` (bounded
//!   summary, not the full project record). `ProjectGet` is invoked
//!   on demand; this cache never holds secrets or credentials.
//! * All async completions are scoped to a request generation, so
//!   stale completions (after a tab is removed or rebound) are dropped
//!   at apply time.
//! * Closing or removing a tab does not delete the underlying session
//!   in the daemon. Removal is a frontend concern only.
//!
//! Compatibility: when the daemon does not advertise
//! `project_catalog.v1` capability, the catalog stays empty and the
//! initial compat tab keeps working as before. The TUI never invents
//! projects.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::protocol::dto::{ProjectDetailsDto, ProjectSummaryDto};
use crate::tui::app::state::async_request::AsyncUiRequestState;
use crate::tui::app::state::project_picker::{SessionSummaryCacheEntry, MAX_OPEN_PROJECT_TABS};

/// A stable, frontend-local identifier for an open project tab.
///
/// These IDs are generated by the TUI (via `ProjectTabId::new`) and
/// survive tab reordering and active-tab changes for the lifetime of
/// the running process. They MUST NOT be reused as `ProjectId` or
/// `SessionId` values; the runtime guarantees they are unique UUID
/// strings distinct from any typed identifier coming from the daemon.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProjectTabId(String);

impl ProjectTabId {
    /// Generate a fresh tab id. UUIDv4 is used to guarantee uniqueness
    /// across the running TUI process and to keep IDs visually
    /// distinguishable from daemon-typed UUIDs (which are accepted as
    /// raw strings in the protocol layer).
    pub fn new() -> Self {
        Self(Uuid::new_v4().to_string())
    }

    /// Borrow the underlying string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for ProjectTabId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ProjectTabId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Bounded cache of project catalog summaries plus the request state
/// for the most recent list/get operation.
///
/// The cache never holds credentials, secret-bearing config, or any
/// field outside the bounded `ProjectSummaryDto` shape. Stale
/// completions are dropped via `AsyncUiRequestState::is_current`.
#[derive(Debug, Default)]
pub struct ProjectCatalogState {
    /// Last successfully loaded project summaries. Bounded by the
    /// daemon's `max_list_items` (defaults to 128).
    pub entries: Vec<ProjectSummaryDto>,
    /// Whether the daemon advertised the project catalog capability.
    /// When `false`, the catalog stays empty and the TUI shows the
    /// current compat tab as the only project context.
    pub capability_supported: bool,
    /// `Some(error)` when the last load attempt failed. Cleared on the
    /// next successful load or by `clear_error`.
    pub last_error: Option<String>,
    /// Whether the catalog was truncated by the daemon. The TUI can
    /// render a small warning when this is true.
    pub truncated: bool,
    /// Async request state for the most recent `ProjectList` request.
    pub list_request: AsyncUiRequestState,
}

impl ProjectCatalogState {
    /// Create a fresh catalog state. Defaults to "capability unknown";
    /// the first successful `ProjectCatalogCapabilities` round-trip
    /// flips this to its actual value.
    pub fn new() -> Self {
        Self::default()
    }

    /// Clear the cached summaries and last error. Does not affect the
    /// async request generation counter; callers that want a fresh
    /// request should call `list_request.begin()` explicitly.
    pub fn clear(&mut self) {
        self.entries.clear();
        self.last_error = None;
        self.truncated = false;
    }

    /// Record a successful list response. Drops the result if the
    /// request generation has been superseded since the load began.
    /// Returns `true` when the result was applied.
    pub fn apply_list(
        &mut self,
        request_id: u64,
        entries: Vec<ProjectSummaryDto>,
        truncated: bool,
    ) -> bool {
        if !self.list_request.finish(request_id) {
            return false;
        }
        self.entries = entries;
        self.truncated = truncated;
        self.last_error = None;
        true
    }

    /// Record a failed list response. Returns `true` when the failure
    /// was applied (i.e., the request was not stale).
    pub fn apply_list_error(&mut self, request_id: u64, error: String) -> bool {
        if !self.list_request.fail(request_id, error.clone()) {
            return false;
        }
        self.last_error = Some(error);
        true
    }

    /// Set the result of a `ProjectCatalogCapabilities` round-trip.
    /// Toggling `capability_supported` to `false` is sticky: the
    /// compat tab continues to work and the catalog stays empty.
    pub fn set_capability(&mut self, supported: bool) {
        self.capability_supported = supported;
    }

    /// Whether a list request is currently in flight.
    pub fn is_loading(&self) -> bool {
        self.list_request.is_loading()
    }

    /// The current list request id (0 when idle).
    pub fn list_request_id(&self) -> u64 {
        self.list_request.request_id()
    }
}

/// The selection state of a single project tab.
///
/// This struct is the canonical projection of one tab's effective
/// project/workspace/session identity and lightweight presentation
/// fields. It deliberately does NOT include the full session messages,
/// history, or git sidebar — those remain on `App.session_state` (the
/// compat surface) for now and will move behind tab scope in later
/// milestones.
#[derive(Debug, Clone)]
pub struct ProjectTabState {
    /// Stable tab id.
    pub tab_id: ProjectTabId,
    /// Human-readable tab label. Defaults to the project display name
    /// or, in compat mode, to the truncated project directory.
    pub label: String,
    /// Daemon-typed project identity. `None` when the tab was created
    /// before the daemon advertised the catalog capability.
    pub project_id: Option<String>,
    /// Daemon-typed workspace identity. `None` until `ProjectGet`
    /// resolves or the daemon reports a default workspace.
    pub workspace_id: Option<String>,
    /// Daemon-typed session identity. `None` when the tab is open but
    /// no session has been selected yet.
    pub session_id: Option<String>,
    /// Selected model identifier for this tab. Mirrors
    /// `App.agent_state.current_model` while this tab is active.
    pub model: String,
    /// Selected agent name for this tab. Mirrors
    /// `App.agent_state.current_agent` while this tab is active.
    pub agent: String,
    /// Per-tab async request state for tab-local refresh operations
    /// (e.g., session list reload, project detail fetch). When a tab
    /// is removed, callers MUST cancel pending requests and bump the
    /// generation so stale completions are dropped.
    pub request_state: AsyncUiRequestState,
    /// Cached project detail for the active tab (from ProjectGet).
    pub project_details: Option<ProjectDetailsDto>,
    /// Mirrors `session_id` but kept separately to avoid confusion
    /// during the switch transaction.
    pub selected_session_id: Option<String>,
    /// Whether a session load is in flight for this tab.
    pub pending_session_load: bool,
    /// Last error from a session load attempt.
    pub last_session_load_error: Option<String>,
    /// Bounded session summary cache (max 256 entries).
    pub session_summaries: Vec<SessionSummaryCacheEntry>,
}

impl ProjectTabState {
    /// Create a fresh tab with a generated id and no daemon-bound
    /// identities. Use [`ProjectTabs::new_tab`] to construct the
    /// container, which assigns the id.
    pub fn empty(tab_id: ProjectTabId, label: String) -> Self {
        Self {
            tab_id,
            label,
            project_id: None,
            workspace_id: None,
            session_id: None,
            model: String::new(),
            agent: String::new(),
            request_state: AsyncUiRequestState::new(),
            project_details: None,
            selected_session_id: None,
            pending_session_load: false,
            last_session_load_error: None,
            session_summaries: Vec::new(),
        }
    }

    /// Stable equality key: two tabs are the "same tab" iff their
    /// `tab_id` matches. Project/workspace/session identities are
    /// expected to change during the tab's lifetime and are not part
    /// of identity.
    pub fn same_tab(&self, other: &Self) -> bool {
        self.tab_id == other.tab_id
    }
}

/// Ordered collection of open project tabs with one designated active
/// tab.
///
/// The collection is keyed by stable `ProjectTabId`s so tabs survive
/// reorder, removal, and active-tab swaps. Mutation goes through the
/// `*_tab` family of helpers; the collection itself stays in a
/// consistent state (`active_tab_id` always points to an open tab if
/// any are open) after every mutation.
#[derive(Debug, Default)]
pub struct ProjectTabs {
    tabs: HashMap<ProjectTabId, ProjectTabState>,
    order: Vec<ProjectTabId>,
    active_tab_id: Option<ProjectTabId>,
}

impl ProjectTabs {
    /// Create an empty container.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a new tab and return its id. The new tab is **not** made
    /// active by default; callers must explicitly call
    /// [`set_active`](Self::set_active) when the new tab should take
    /// focus. Use this when a tab is opened in the background (e.g.,
    /// "open in new tab" semantics).
    pub fn add_tab(&mut self, tab: ProjectTabState) -> ProjectTabId {
        let id = tab.tab_id.clone();
        debug_assert!(
            !self.tabs.contains_key(&id),
            "tab id {:?} already exists in ProjectTabs",
            id
        );
        self.tabs.insert(id.clone(), tab);
        if !self.order.contains(&id) {
            self.order.push(id.clone());
        }
        id
    }

    /// Add a new tab and immediately make it active. The previous
    /// active tab (if any) keeps its position in the order; the new
    /// tab is appended to the end.
    pub fn add_and_activate(&mut self, tab: ProjectTabState) -> ProjectTabId {
        let id = self.add_tab(tab);
        self.active_tab_id = Some(id.clone());
        id
    }

    /// Remove a tab by id. If the removed tab was active, the active
    /// id falls back to the previous tab in display order; if no tabs
    /// remain, `active_tab_id` becomes `None`.
    ///
    /// Removal bumps the per-tab request generation so stale
    /// completions cannot mutate the removed tab. This method does NOT
    /// delete any daemon session — it is a frontend concern only.
    pub fn remove_tab(&mut self, tab_id: &ProjectTabId) -> Option<ProjectTabState> {
        let removed = self.tabs.remove(tab_id);
        if removed.is_some() {
            self.order.retain(|id| id != tab_id);
            if self.active_tab_id.as_ref() == Some(tab_id) {
                self.active_tab_id = self.order.last().cloned();
            }
        }
        removed
    }

    /// Set the active tab by id. Returns `true` if the id matches an
    /// open tab, `false` otherwise (in which case the active id is
    /// left unchanged).
    pub fn set_active(&mut self, tab_id: &ProjectTabId) -> bool {
        if self.tabs.contains_key(tab_id) {
            self.active_tab_id = Some(tab_id.clone());
            true
        } else {
            false
        }
    }

    /// The currently active tab, if any.
    pub fn active(&self) -> Option<&ProjectTabState> {
        let id = self.active_tab_id.as_ref()?;
        self.tabs.get(id)
    }

    /// Mutable accessor for the active tab. Returns `None` when no
    /// tabs are open or when the active id does not resolve (which
    /// should only happen after manual mutation).
    pub fn active_mut(&mut self) -> Option<&mut ProjectTabState> {
        let id = self.active_tab_id.clone()?;
        self.tabs.get_mut(&id)
    }

    /// Lookup a tab by id (immutable).
    pub fn get(&self, tab_id: &ProjectTabId) -> Option<&ProjectTabState> {
        self.tabs.get(tab_id)
    }

    /// Lookup a tab by id (mutable).
    pub fn get_mut(&mut self, tab_id: &ProjectTabId) -> Option<&mut ProjectTabState> {
        self.tabs.get_mut(tab_id)
    }

    /// All open tabs in display order.
    pub fn ordered(&self) -> Vec<&ProjectTabState> {
        self.order
            .iter()
            .filter_map(|id| self.tabs.get(id))
            .collect()
    }

    /// The active tab id, if any. Distinct from `active()` so callers
    /// can compare ids without taking a reference to the full state.
    pub fn active_tab_id(&self) -> Option<&ProjectTabId> {
        self.active_tab_id.as_ref()
    }

    /// Number of open tabs.
    pub fn len(&self) -> usize {
        self.tabs.len()
    }

    /// Whether no tabs are open.
    pub fn is_empty(&self) -> bool {
        self.tabs.is_empty()
    }

    /// Find tabs whose project_id matches the given daemon id. Used
    /// when resolving catalog entries to existing tabs.
    pub fn find_by_project(&self, project_id: &str) -> Option<&ProjectTabState> {
        self.tabs
            .values()
            .find(|t| t.project_id.as_deref() == Some(project_id))
    }

    /// Update the daemon-side identities for the active tab. No-op when
    /// no tab is active. Used by the startup compatibility path and
    /// future picker "open project" handlers.
    pub fn set_active_identities(
        &mut self,
        project_id: Option<String>,
        workspace_id: Option<String>,
        session_id: Option<String>,
    ) {
        if let Some(tab) = self.active_mut() {
            tab.project_id = project_id;
            tab.workspace_id = workspace_id;
            tab.session_id = session_id;
        }
    }

    /// Build a compatibility tab from the legacy single-project
    /// startup state. The tab inherits `project_dir` as its label and
    /// uses daemon-typed ids when available. The container is
    /// guaranteed to have exactly one tab and that tab will be active.
    pub fn from_compat(
        project_dir: &str,
        project_id: Option<String>,
        workspace_id: Option<String>,
        session_id: Option<String>,
        model: &str,
        agent: &str,
    ) -> Self {
        let tab_id = ProjectTabId::new();
        let label = if project_dir.is_empty() {
            "default".to_string()
        } else {
            // Use the trailing component(s) of the project directory as
            // a human label. Avoid pulling in PathBuf dependency here
            // by using string split; the legacy `project_dir` is
            // already canonicalized.
            let trimmed = project_dir.trim_end_matches('/');
            match trimmed.rsplit_once('/') {
                Some((_, tail)) if !tail.is_empty() => tail.to_string(),
                _ => trimmed.to_string(),
            }
        };
        let tab = ProjectTabState {
            tab_id: tab_id.clone(),
            label,
            project_id,
            workspace_id,
            session_id,
            model: model.to_string(),
            agent: agent.to_string(),
            request_state: AsyncUiRequestState::new(),
            project_details: None,
            selected_session_id: None,
            pending_session_load: false,
            last_session_load_error: None,
            session_summaries: Vec::new(),
        };
        let mut tabs = Self::new();
        tabs.add_tab(tab);
        tabs.active_tab_id = Some(tab_id);
        tabs
    }

    /// Whether the tab container has reached its maximum capacity.
    pub fn is_at_capacity(&self) -> bool {
        self.tabs.len() >= MAX_OPEN_PROJECT_TABS
    }

    /// When the last real tab is removed, create a fresh empty compat
    /// tab and return its id. Guarantees render paths always have at
    /// least one tab.
    pub fn close_fallback_tab(&mut self) -> ProjectTabId {
        let tab_id = ProjectTabId::new();
        let tab = ProjectTabState {
            tab_id: tab_id.clone(),
            label: "default".to_string(),
            project_id: None,
            workspace_id: None,
            session_id: None,
            model: String::new(),
            agent: String::new(),
            request_state: AsyncUiRequestState::new(),
            project_details: None,
            selected_session_id: None,
            pending_session_load: false,
            last_session_load_error: None,
            session_summaries: Vec::new(),
        };
        self.add_and_activate(tab);
        tab_id
    }

    /// Display labels with disambiguation for duplicates.
    /// When two tabs have identical labels, appends a short stable
    /// suffix derived from workspace_id or tab_id — never from a path.
    pub fn display_labels(&self) -> Vec<(ProjectTabId, String)> {
        use crate::tui::app::state::project_picker::disambiguate_label;

        let ordered = self.ordered();
        let mut result = Vec::with_capacity(ordered.len());

        // Count label occurrences
        let mut label_counts: HashMap<String, usize> = HashMap::new();
        for tab in &ordered {
            *label_counts.entry(tab.label.clone()).or_insert(0) += 1;
        }

        for tab in &ordered {
            let needs_disambig = label_counts.get(&tab.label).copied().unwrap_or(0) > 1;
            let label = if needs_disambig {
                let suffix_src = tab
                    .workspace_id
                    .as_deref()
                    .unwrap_or_else(|| tab.tab_id.as_str());
                disambiguate_label(&tab.label, suffix_src)
            } else {
                crate::tui::app::state::project_picker::truncate_tab_label(&tab.label)
            };
            result.push((tab.tab_id.clone(), label));
        }

        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_tab(label: &str) -> ProjectTabState {
        ProjectTabState::empty(ProjectTabId::new(), label.to_string())
    }

    #[test]
    fn project_tab_id_is_unique() {
        let a = ProjectTabId::new();
        let b = ProjectTabId::new();
        assert_ne!(a, b);
        assert!(!a.as_str().is_empty());
        assert!(!b.as_str().is_empty());
    }

    #[test]
    fn add_and_activate_sets_active() {
        let mut tabs = ProjectTabs::new();
        let id = tabs.add_and_activate(empty_tab("first"));
        assert_eq!(tabs.active_tab_id(), Some(&id));
        assert_eq!(tabs.len(), 1);
        assert_eq!(tabs.ordered().len(), 1);
    }

    #[test]
    fn add_tab_does_not_change_active() {
        let mut tabs = ProjectTabs::new();
        let first = tabs.add_and_activate(empty_tab("first"));
        let _second = tabs.add_tab(empty_tab("second"));
        assert_eq!(tabs.active_tab_id(), Some(&first));
        assert_eq!(tabs.len(), 2);
    }

    #[test]
    fn set_active_clamps_unknown_id() {
        let mut tabs = ProjectTabs::new();
        let _ = tabs.add_and_activate(empty_tab("first"));
        let bogus = ProjectTabId::new();
        assert!(!tabs.set_active(&bogus));
        assert!(tabs.active().is_some());
    }

    #[test]
    fn remove_active_falls_back_to_last_in_order() {
        let mut tabs = ProjectTabs::new();
        let a = tabs.add_and_activate(empty_tab("a"));
        let b = tabs.add_tab(empty_tab("b"));
        let c = tabs.add_tab(empty_tab("c"));
        // Order: [a, b, c]; active is a. Remove a -> active falls back
        // to the last in order, which is c.
        let removed = tabs.remove_tab(&a).expect("remove a");
        assert_eq!(removed.label, "a");
        assert_eq!(tabs.active_tab_id(), Some(&c));
        assert_eq!(tabs.ordered().len(), 2);
        assert_eq!(tabs.ordered()[0].tab_id, b);
        assert_eq!(tabs.ordered()[1].tab_id, c);
    }

    #[test]
    fn remove_non_active_keeps_active() {
        let mut tabs = ProjectTabs::new();
        let a = tabs.add_and_activate(empty_tab("a"));
        let b = tabs.add_tab(empty_tab("b"));
        let c = tabs.add_tab(empty_tab("c"));
        let _ = tabs.remove_tab(&b);
        assert_eq!(tabs.active_tab_id(), Some(&a));
        let order: Vec<&ProjectTabId> = tabs.ordered().iter().map(|t| &t.tab_id).collect();
        assert_eq!(order, vec![&a, &c]);
    }

    #[test]
    fn remove_last_tab_clears_active() {
        let mut tabs = ProjectTabs::new();
        let id = tabs.add_and_activate(empty_tab("only"));
        tabs.remove_tab(&id);
        assert!(tabs.active().is_none());
        assert_eq!(tabs.active_tab_id(), None);
        assert!(tabs.is_empty());
    }

    #[test]
    fn identical_session_titles_across_projects_do_not_collide() {
        let mut tabs = ProjectTabs::new();
        let mut a = empty_tab("alpha");
        a.project_id = Some("project-a".to_string());
        a.session_id = Some("session-1".to_string());
        let mut b = empty_tab("beta");
        b.project_id = Some("project-b".to_string());
        b.session_id = Some("session-1".to_string());
        let id_a = tabs.add_and_activate(a);
        let id_b = tabs.add_tab(b);
        assert_ne!(id_a, id_b);
        assert_eq!(tabs.len(), 2);
        let session_a = tabs.get(&id_a).and_then(|t| t.session_id.clone()).unwrap();
        let session_b = tabs.get(&id_b).and_then(|t| t.session_id.clone()).unwrap();
        assert_eq!(session_a, session_b);
        assert_ne!(id_a, id_b);
    }

    #[test]
    fn per_tab_model_and_agent_are_independent() {
        let mut tabs = ProjectTabs::new();
        let mut a = empty_tab("alpha");
        a.model = "model-a".to_string();
        a.agent = "agent-a".to_string();
        let mut b = empty_tab("beta");
        b.model = "model-b".to_string();
        b.agent = "agent-b".to_string();
        let id_a = tabs.add_and_activate(a);
        let id_b = tabs.add_tab(b);
        assert_eq!(tabs.get(&id_a).unwrap().model, "model-a");
        assert_eq!(tabs.get(&id_b).unwrap().model, "model-b");
        assert_eq!(tabs.get(&id_a).unwrap().agent, "agent-a");
        assert_eq!(tabs.get(&id_b).unwrap().agent, "agent-b");
    }

    #[test]
    fn find_by_project_returns_open_tab() {
        let mut tabs = ProjectTabs::new();
        let mut a = empty_tab("alpha");
        a.project_id = Some("project-a".to_string());
        let mut b = empty_tab("beta");
        b.project_id = Some("project-b".to_string());
        let _ = tabs.add_and_activate(a);
        let _ = tabs.add_tab(b);
        let found = tabs.find_by_project("project-b").unwrap();
        assert_eq!(found.label, "beta");
        assert!(tabs.find_by_project("project-c").is_none());
    }

    #[test]
    fn from_compat_creates_one_active_tab() {
        let tabs = ProjectTabs::from_compat(
            "/home/u/work/foo",
            Some("p".to_string()),
            Some("w".to_string()),
            Some("s".to_string()),
            "model-x",
            "agent-x",
        );
        assert_eq!(tabs.len(), 1);
        let active = tabs.active().unwrap();
        assert_eq!(active.project_id.as_deref(), Some("p"));
        assert_eq!(active.workspace_id.as_deref(), Some("w"));
        assert_eq!(active.session_id.as_deref(), Some("s"));
        assert_eq!(active.model, "model-x");
        assert_eq!(active.agent, "agent-x");
        assert_eq!(active.label, "foo");
    }

    #[test]
    fn from_compat_empty_dir_falls_back_to_default_label() {
        let tabs = ProjectTabs::from_compat("", None, None, None, "", "");
        let active = tabs.active().unwrap();
        assert_eq!(active.label, "default");
    }

    #[test]
    fn set_active_identities_only_mutates_active() {
        let mut tabs = ProjectTabs::new();
        let _first = tabs.add_and_activate(empty_tab("first"));
        let second = tabs.add_tab(empty_tab("second"));
        tabs.set_active_identities(
            Some("p".to_string()),
            Some("w".to_string()),
            Some("s".to_string()),
        );
        let active = tabs.active().unwrap();
        assert_eq!(active.project_id.as_deref(), Some("p"));
        let other = tabs.get(&second).unwrap();
        assert!(other.project_id.is_none());
    }

    #[test]
    fn catalog_state_apply_list_drops_stale_results() {
        let mut state = ProjectCatalogState::new();
        let id1 = state.list_request.begin();
        let id2 = state.list_request.begin();
        let applied = state.apply_list(id1, Vec::new(), false);
        assert!(!applied);
        let applied = state.apply_list(id2, Vec::new(), false);
        assert!(applied);
    }

    #[test]
    fn catalog_state_apply_list_error_records_failure() {
        let mut state = ProjectCatalogState::new();
        let id = state.list_request.begin();
        let applied = state.apply_list_error(id, "boom".to_string());
        assert!(applied);
        assert_eq!(state.last_error.as_deref(), Some("boom"));
        assert!(!state.is_loading());
    }

    #[test]
    fn catalog_state_clear_resets_error_and_entries() {
        let mut state = ProjectCatalogState::new();
        let id = state.list_request.begin();
        state.apply_list_error(id, "boom".to_string());
        state.clear();
        assert!(state.entries.is_empty());
        assert!(state.last_error.is_none());
        assert!(!state.truncated);
    }

    #[test]
    fn ordered_reflects_insertion_order() {
        let mut tabs = ProjectTabs::new();
        let a = tabs.add_and_activate(empty_tab("a"));
        let _b = tabs.add_tab(empty_tab("b"));
        let c = tabs.add_tab(empty_tab("c"));
        let order: Vec<&str> = tabs.ordered().iter().map(|t| t.label.as_str()).collect();
        assert_eq!(order, vec!["a", "b", "c"]);
        // active_tab_id still points to a.
        assert_eq!(tabs.active_tab_id(), Some(&a));
        assert_eq!(tabs.len(), 3);
        assert_eq!(c, c);
    }
}
