#!/usr/bin/env python3
"""Generate Rust source files from TOML agent definitions.

Reads `*.toml` from `assets/agents/` and `*.md` prompt files from
`assets/prompts/agents/`, then writes:
  - `src/agent/builtins/generated.rs`
  - `src/agent/builtins/mod.rs`

Requires Python 3.11+ (uses tomllib from stdlib).

Usage:
    python3 scripts/generate_builtin_agents.py           # generate
    python3 scripts/generate_builtin_agents.py --check   # verify mode (CI)
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

import tomllib

OUTPUT_GENERATED_RS = "src/agent/builtins/generated.rs"
OUTPUT_MOD_RS = "src/agent/builtins/mod.rs"

HEADER = "// AUTO-GENERATED by scripts/generate_builtin_agents.py — DO NOT EDIT"

DEFAULT_PROMPT_PATTERNS = (
    "uses the default",
    "no custom prompt",
    "default system prompt",
)

PROMPT_HEADING_RE = re.compile(r"^#\s+\S+.*$", re.MULTILINE)

# Allowed values for schema validation
VALID_MODES = {"Primary", "Subagent", "All"}
VALID_PERMISSION_ACTIONS = {"allow", "ask", "deny"}
VALID_RUNTIME_KINDS = {"standard", "security_review", "research", "compaction", "title", "summary"}

# All recognised top-level keys under [agent]
KNOWN_AGENT_KEYS = {
    "name", "role", "description", "mode", "hidden",
    "temperature", "steps", "color", "prompt_file", "permissions",
    "model", "fallback_model", "runtime_kind",
}


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _read_prompt(prompt_path: Path) -> str | None:
    """Read a prompt markdown file, strip the heading, return trimmed content.

    Returns None if the file is missing or contains only a default/placeholder note.
    """
    if not prompt_path.is_file():
        return None

    text = prompt_path.read_text(encoding="utf-8").strip()
    if not text:
        return None

    lower = text.lower()
    if any(pat in lower for pat in DEFAULT_PROMPT_PATTERNS):
        return None

    # Strip the first `# name` heading line
    text = PROMPT_HEADING_RE.sub("", text, count=1).strip()
    return text or None


def _format_string_literal(s: str) -> str:
    """Return a Rust String expression with proper escaping."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}".to_string()'


def _format_option_string(s: str | None) -> str:
    if s is None:
        return "None"
    return f"Some({_format_string_literal(s)})"


def _format_option_f64(v: float | None) -> str:
    if v is None:
        return "None"
    return f"Some({v})"


def _format_option_usize(v: int | None) -> str:
    if v is None:
        return "None"
    return f"Some({v})"


def _format_permissions(perms: dict[str, str]) -> str:
    """Return a Rust HashMap literal for permissions."""
    if not perms:
        return "HashMap::new()"
    entries = []
    for key, val in sorted(perms.items()):
        entries.append(
            f'                ({_format_string_literal(key)}, {_format_string_literal(val)}),'
        )
    inner = "\n".join(entries)
    return f"HashMap::from([\n{inner}\n            ])"


def _validate_agent(agent: dict, toml_path: Path, agent_dir: Path) -> list[str]:
    """Validate a single agent TOML table.  Returns a list of error strings."""
    errors: list[str] = []
    prefix = str(toml_path.relative_to(agent_dir.parent.parent))

    # --- Unknown top-level keys ---
    unknown = set(agent.keys()) - KNOWN_AGENT_KEYS
    if unknown:
        errors.append(f"{prefix}: unknown top-level keys: {', '.join(sorted(unknown))}")

    # --- Required name ---
    if "name" not in agent:
        errors.append(f"{prefix}: missing required 'name' field")
        return errors  # can't validate further without a name

    name = agent["name"]

    # --- Duplicate name handled externally ---

    # --- Mode validation ---
    mode = agent.get("mode", "Primary")
    if mode not in VALID_MODES:
        errors.append(f"{prefix} agent '{name}': invalid mode '{mode}' (expected one of {', '.join(sorted(VALID_MODES))})")

    # --- Description required for non-hidden agents ---
    hidden = agent.get("hidden", False)
    if not hidden and not agent.get("description"):
        errors.append(f"{prefix} agent '{name}': missing 'description' (required for visible agents)")

    # --- Permission action validation ---
    permissions = agent.get("permissions", {})
    for perm_key, perm_val in permissions.items():
        if perm_val not in VALID_PERMISSION_ACTIONS:
            errors.append(
                f"{prefix} agent '{name}': permission '{perm_key}' has invalid action '{perm_val}' "
                f"(expected one of {', '.join(sorted(VALID_PERMISSION_ACTIONS))})"
            )

    # --- Prompt file validation ---
    prompt_file_rel = agent.get("prompt_file")
    if prompt_file_rel:
        prompt_path = agent_dir.parent / prompt_file_rel
        if not prompt_path.is_file():
            errors.append(f"{prefix} agent '{name}': prompt_file '{prompt_file_rel}' does not exist")
        # Ensure prompt file is under assets/
        try:
            prompt_path.resolve().relative_to((agent_dir.parent).resolve())
        except ValueError:
            errors.append(f"{prefix} agent '{name}': prompt_file '{prompt_file_rel}' is outside assets/ directory")

    # --- Runtime kind validation ---
    runtime_kind = agent.get("runtime_kind")
    if runtime_kind is not None and runtime_kind not in VALID_RUNTIME_KINDS:
        errors.append(
            f"{prefix} agent '{name}': invalid runtime_kind '{runtime_kind}' "
            f"(expected one of {', '.join(sorted(VALID_RUNTIME_KINDS))})"
        )

    return errors


def _parse_agent_toml(toml_path: Path, agent_dir: Path) -> tuple[dict, list[str]]:
    """Parse and validate a TOML agent file.  Returns (agent_table, errors)."""
    with open(toml_path, "rb") as f:
        data = tomllib.load(f)
    if "agent" not in data:
        return {}, [f"{toml_path.name}: missing [agent] table"]
    agent = data["agent"]
    errors = _validate_agent(agent, toml_path, agent_dir)
    return agent, errors


def _build_agent_entry(agent: dict, prompt_content: str | None) -> str:
    """Return a Rust `Agent { ... }` expression string."""
    name = agent["name"]
    description = agent.get("description", "")
    mode_str = agent.get("mode", "Primary")
    hidden = agent.get("hidden", False)
    role = agent.get("role")
    permissions = agent.get("permissions", {})
    temperature = agent.get("temperature")
    steps = agent.get("steps")
    color = agent.get("color")
    model = agent.get("model")
    fallback_model = agent.get("fallback_model")
    runtime_kind = agent.get("runtime_kind")

    mode_variant = {
        "Primary": "AgentMode::Primary",
        "Subagent": "AgentMode::Subagent",
        "All": "AgentMode::All",
    }.get(mode_str)

    # Mode validation is handled by _validate_agent; fall back gracefully
    if mode_variant is None:
        mode_variant = "AgentMode::Primary"

    def _format_runtime_kind(kind: str | None) -> str:
        if kind is None:
            return "None"
        variant = {
            "standard": "AgentRuntimeKind::Standard",
            "security_review": "AgentRuntimeKind::SecurityReview",
            "research": "AgentRuntimeKind::Research",
            "compaction": "AgentRuntimeKind::Compaction",
            "title": "AgentRuntimeKind::Title",
            "summary": "AgentRuntimeKind::Summary",
        }.get(kind)
        if variant is None:
            return "None"
        return f"Some({variant})"

    lines = []
    lines.append("        Agent {")
    lines.append(f"            name: {_format_string_literal(name)},")
    lines.append(f"            role: {_format_option_string(role)},")
    lines.append(f"            description: {_format_string_literal(description)},")
    lines.append(f"            mode: {mode_variant},")
    lines.append("            mode_name: None,")
    lines.append(f"            model: {_format_option_string(model)},")
    lines.append(f"            fallback_model: {_format_option_string(fallback_model)},")
    lines.append("            variant: None,")
    lines.append(f"            temperature: {_format_option_f64(temperature)},")
    lines.append("            top_p: None,")
    lines.append(f"            color: {_format_option_string(color)},")
    lines.append(f"            steps: {_format_option_usize(steps)},")
    lines.append(f"            system_prompt: {_format_option_string(prompt_content)},")
    lines.append(f"            permissions: {_format_permissions(permissions)},")
    lines.append(f"            hidden: {'true' if hidden else 'false'},")
    lines.append("            thinking_budget: None,")
    lines.append("            reasoning_effort: None,")
    lines.append(f"            runtime_kind: {_format_runtime_kind(runtime_kind)},")
    lines.append("        }")

    return "\n".join(lines)


def _build_generated_rs(agents: list[tuple[str, str]]) -> str:
    """Return the full content of generated.rs."""
    entries = ",\n".join(expr for _, expr in agents)
    return (
        f"{HEADER}\n"
        "\n"
        "use crate::agent::{Agent, AgentMode, AgentRuntimeKind};\n"
        "use std::collections::HashMap;\n"
        "\n"
        "pub fn generated_builtin_agents() -> Vec<Agent> {\n"
        "    vec![\n"
        f"{entries},\n"
        "    ]\n"
        "}\n"
    )


def _build_mod_rs() -> str:
    """Return the full content of mod.rs."""
    return (
        f"{HEADER}\n"
        "\n"
        "mod generated;\n"
        "pub use generated::generated_builtin_agents;\n"
    )


def load_and_validate(repo_root: Path) -> tuple[list[tuple[str, str]], list[str]]:
    """Load all TOML agents, validate, and return (agents, all_errors)."""
    agent_dir = repo_root / "assets" / "agents"
    prompt_dir = repo_root / "assets" / "prompts" / "agents"

    if not agent_dir.is_dir():
        return [], [f"agent directory not found: {agent_dir}"]

    toml_files = sorted(agent_dir.glob("*.toml"))
    if not toml_files:
        return [], [f"no .toml files found in {agent_dir}"]

    all_errors: list[str] = []
    agents: list[tuple[str, str]] = []
    seen_names: set[str] = set()

    for toml_path in toml_files:
        agent, errors = _parse_agent_toml(toml_path, agent_dir)
        all_errors.extend(errors)

        if not agent or "name" not in agent:
            continue

        name = agent["name"]

        # Duplicate name check
        if name in seen_names:
            all_errors.append(f"{toml_path.name}: duplicate agent name '{name}'")
            continue
        seen_names.add(name)

        # Resolve prompt
        prompt_file_rel = agent.pop("prompt_file", None)
        if prompt_file_rel:
            prompt_path = repo_root / "assets" / prompt_file_rel
        else:
            prompt_path = prompt_dir / f"{name}.md"
        prompt_content = _read_prompt(prompt_path)

        rust_expr = _build_agent_entry(agent, prompt_content)
        agents.append((name, rust_expr))

    # Sort by name for deterministic output
    agents.sort(key=lambda a: a[0])

    return agents, all_errors


def generate(repo_root: Path) -> None:
    """Generate generated.rs and mod.rs from TOML definitions."""
    agents, errors = load_and_validate(repo_root)

    if errors:
        print("Schema validation errors:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        sys.exit(1)

    print(f"Generating from {len(agents)} agent definition(s)...")

    out_generated = repo_root / OUTPUT_GENERATED_RS
    out_mod = repo_root / OUTPUT_MOD_RS

    # Build and write generated.rs
    generated_rs = _build_generated_rs(agents)
    out_generated.parent.mkdir(parents=True, exist_ok=True)
    out_generated.write_text(generated_rs, encoding="utf-8")
    print(f"Wrote {out_generated}")

    # Build and write mod.rs
    mod_rs = _build_mod_rs()
    out_mod.write_text(mod_rs, encoding="utf-8")
    print(f"Wrote {out_mod}")


def check(repo_root: Path) -> None:
    """Compare generated output against checked-in files. Exit 1 on drift."""
    agents, errors = load_and_validate(repo_root)

    if errors:
        print("Schema validation errors:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        sys.exit(1)

    print(f"Checking {len(agents)} agent definition(s)...")

    expected_generated = _build_generated_rs(agents)
    expected_mod = _build_mod_rs()

    out_generated = repo_root / OUTPUT_GENERATED_RS
    out_mod = repo_root / OUTPUT_MOD_RS

    drift = False

    # Check generated.rs
    if out_generated.is_file():
        actual_generated = out_generated.read_text(encoding="utf-8")
        if actual_generated != expected_generated:
            diff = difflib.unified_diff(
                actual_generated.splitlines(keepends=True),
                expected_generated.splitlines(keepends=True),
                fromfile=OUTPUT_GENERATED_RS,
                tofile=f"{OUTPUT_GENERATED_RS} (expected)",
            )
            print(f"DRIFT in {OUTPUT_GENERATED_RS}:", file=sys.stderr)
            sys.stderr.writelines(diff)
            drift = True
        else:
            print(f"  {OUTPUT_GENERATED_RS}: OK")
    else:
        print(f"  {OUTPUT_GENERATED_RS}: MISSING (run generate)", file=sys.stderr)
        drift = True

    # Check mod.rs
    if out_mod.is_file():
        actual_mod = out_mod.read_text(encoding="utf-8")
        if actual_mod != expected_mod:
            diff = difflib.unified_diff(
                actual_mod.splitlines(keepends=True),
                expected_mod.splitlines(keepends=True),
                fromfile=OUTPUT_MOD_RS,
                tofile=f"{OUTPUT_MOD_RS} (expected)",
            )
            print(f"DRIFT in {OUTPUT_MOD_RS}:", file=sys.stderr)
            sys.stderr.writelines(diff)
            drift = True
        else:
            print(f"  {OUTPUT_MOD_RS}: OK")
    else:
        print(f"  {OUTPUT_MOD_RS}: MISSING (run generate)", file=sys.stderr)
        drift = True

    # Determinism check: generate twice, compare
    agents2, _ = load_and_validate(repo_root)
    if agents != agents2:
        print("DETERMINISM FAILURE: two consecutive loads produced different results", file=sys.stderr)
        drift = True

    if drift:
        print("\nRun: python3 scripts/generate_builtin_agents.py", file=sys.stderr)
        sys.exit(1)

    print("All checks passed.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Rust agent source files from TOML definitions."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify checked-in output matches TOML definitions (for CI).",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Path to the repository root (defaults to parent of scripts/).",
    )
    args = parser.parse_args()

    repo_root: Path = args.repo_root if args.repo_root else _repo_root()
    repo_root = repo_root.resolve()

    if not repo_root.is_dir():
        print(f"Error: repo root does not exist: {repo_root}", file=sys.stderr)
        sys.exit(1)

    try:
        if args.check:
            check(repo_root)
        else:
            generate(repo_root)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
