#!/usr/bin/env python3
"""Generate Rust source files from TOML agent definitions.

Reads `*.toml` from `assets/agents/` and `*.md` prompt files from
`assets/prompts/agents/`, then writes:
  - `src/agent/builtins/generated.rs`
  - `src/agent/builtins/mod.rs`

Requires Python 3.11+ (uses tomllib from stdlib).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import tomllib

OUTPUT_GENERATED_RS = "src/agent/builtins/generated.rs"
OUTPUT_MOD_RS = "src/agent/builtins/mod.rs"

HEADER = "// AUTO-GENERATED by scripts/generate_builtin_agents.py — DO NOT EDIT"

DEFAULT_PROMPT_PATTERNS = (
    "uses the default",
    "no custom prompt",
    "default system prompt",
)

PROMPT_HEADING_RE = re.compile(r"^#\s+\S+.*$", re.MULTILINE)


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _read_prompt(prompt_path: Path) -> str | None:
    """Read a prompt markdown file, strip the heading, return trimmed content.

    Returns None if the file is missing or contains only a default/placeholder note.
    """
    if not prompt_path.is_file():
        return None

    text = prompt_path.read_text(encoding="utf-8").strip()
    if not text:
        return None

    lower = text.lower()
    if any(pat in lower for pat in DEFAULT_PROMPT_PATTERNS):
        return None

    # Strip the first `# name` heading line
    text = PROMPT_HEADING_RE.sub("", text, count=1).strip()
    return text or None


def _format_string_literal(s: str) -> str:
    """Return a Rust String expression with proper escaping."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}".to_string()'


def _format_option_string(s: str | None) -> str:
    if s is None:
        return "None"
    return f"Some({_format_string_literal(s)})"


def _format_permissions(perms: dict[str, str]) -> str:
    """Return a Rust HashMap literal for permissions."""
    if not perms:
        return "HashMap::new()"
    entries = []
    for key, val in sorted(perms.items()):
        entries.append(
            f'                ({_format_string_literal(key)}, {_format_string_literal(val)}),'
        )
    inner = "\n".join(entries)
    return f"HashMap::from([\n{inner}\n            ])"


def _parse_agent_toml(toml_path: Path) -> dict:
    """Parse a TOML agent file and return the [agent] table."""
    with open(toml_path, "rb") as f:
        data = tomllib.load(f)
    if "agent" not in data:
        raise ValueError(f"{toml_path}: missing [agent] table")
    return data["agent"]


def _build_agent_entry(agent: dict, prompt_content: str | None) -> str:
    """Return a Rust `Agent { ... }` expression string."""
    name = agent["name"]
    description = agent.get("description", "")
    mode_str = agent.get("mode", "Primary")
    hidden = agent.get("hidden", False)
    role = agent.get("role")
    permissions = agent.get("permissions", {})

    mode_variant = {
        "Primary": "AgentMode::Primary",
        "Subagent": "AgentMode::Subagent",
        "All": "AgentMode::All",
    }.get(mode_str)

    if mode_variant is None:
        raise ValueError(f"Agent '{name}': unknown mode '{mode_str}'")

    lines = []
    lines.append("        Agent {")
    lines.append(f"            name: {_format_string_literal(name)},")
    lines.append(f"            role: {_format_option_string(role)},")
    lines.append(f"            description: {_format_string_literal(description)},")
    lines.append(f"            mode: {mode_variant},")
    lines.append("            mode_name: None,")
    lines.append("            model: None,")
    lines.append("            variant: None,")
    lines.append("            temperature: None,")
    lines.append("            top_p: None,")
    lines.append("            color: None,")
    lines.append("            steps: None,")
    lines.append(f"            system_prompt: {_format_option_string(prompt_content)},")
    lines.append(f"            permissions: {_format_permissions(permissions)},")
    lines.append(f"            hidden: {'true' if hidden else 'false'},")
    lines.append("            thinking_budget: None,")
    lines.append("            reasoning_effort: None,")
    lines.append("        }")

    return "\n".join(lines)


def generate(repo_root: Path) -> None:
    agent_dir = repo_root / "assets" / "agents"
    prompt_dir = repo_root / "assets" / "prompts" / "agents"
    out_generated = repo_root / OUTPUT_GENERATED_RS
    out_mod = repo_root / OUTPUT_MOD_RS

    if not agent_dir.is_dir():
        print(f"Error: agent directory not found: {agent_dir}", file=sys.stderr)
        sys.exit(1)

    toml_files = sorted(agent_dir.glob("*.toml"))
    if not toml_files:
        print(f"Error: no .toml files found in {agent_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Generating from {len(toml_files)} agent definition(s)...")

    agents: list[tuple[str, str]] = []  # (name, rust_expr)

    for toml_path in toml_files:
        agent = _parse_agent_toml(toml_path)
        name = agent["name"]

        prompt_path = prompt_dir / f"{name}.md"
        prompt_content = _read_prompt(prompt_path)

        print(f"  {name}: prompt={'yes' if prompt_content else 'none'}")

        rust_expr = _build_agent_entry(agent, prompt_content)
        agents.append((name, rust_expr))

    # Sort by name for deterministic output
    agents.sort(key=lambda a: a[0])

    # Build generated.rs
    entries = ",\n".join(expr for _, expr in agents)
    generated_rs = (
        f"{HEADER}\n"
        "\n"
        "use std::collections::HashMap;\n"
        "use crate::agent::{Agent, AgentMode};\n"
        "\n"
        "pub fn generated_builtin_agents() -> Vec<Agent> {\n"
        "    vec![\n"
        f"{entries},\n"
        "    ]\n"
        "}\n"
    )

    out_generated.parent.mkdir(parents=True, exist_ok=True)
    out_generated.write_text(generated_rs, encoding="utf-8")
    print(f"Wrote {out_generated}")

    # Build mod.rs
    mod_rs = (
        f"{HEADER}\n"
        "\n"
        "mod generated;\n"
        "pub use generated::generated_builtin_agents;\n"
    )

    out_mod.write_text(mod_rs, encoding="utf-8")
    print(f"Wrote {out_mod}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Rust agent source files from TOML definitions."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Path to the repository root (defaults to parent of scripts/).",
    )
    args = parser.parse_args()

    repo_root: Path = args.repo_root if args.repo_root else _repo_root()
    repo_root = repo_root.resolve()

    if not repo_root.is_dir():
        print(f"Error: repo root does not exist: {repo_root}", file=sys.stderr)
        sys.exit(1)

    try:
        generate(repo_root)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
