#![deny(unsafe_code)]

pub mod agent;
pub mod model_profile;
pub mod crypto;
pub mod exec;
pub mod hooks;
pub mod ide;
pub mod memory;
pub mod security;
pub mod tts;

pub use tts::TtsEngine;
pub mod bus;
#[cfg(feature = "server")]
pub mod client;
pub mod command;
pub mod config;
pub mod error;
pub mod goal;
pub mod lsp;
pub mod mcp;
pub mod permission;
pub mod plugin;
pub mod protocol;
pub mod core;
pub mod provider;
pub mod shell_session;
pub mod resilience;
#[cfg(feature = "server")]
pub mod server;
pub mod session;
pub mod skills;
pub mod snapshot;
pub mod storage;
pub mod tool;
pub mod tui;
pub mod upgrade;
pub mod util;
pub mod worktree;
pub mod research;
pub mod task_state;
