use serde::{Deserialize, Serialize};

/// Identifies where a Git command originated. Metadata only — does not
/// change operation semantics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum GitCommandOrigin {
    /// Parsed from a native tool invocation.
    NativeTool,
    /// Translated from a Bash/shell command.
    BashTranslation,
    /// Generated by a workflow or automation.
    Workflow,
    /// Triggered from the TUI.
    Tui,
}
