use serde::{Deserialize, Serialize};

/// Identifies where a Git command originated. Metadata only — does not
/// change operation semantics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum GitCommandOrigin {
    /// Parsed from a native tool invocation.
    NativeTool,
    /// Translated from a Bash/shell command.
    BashTranslation,
    /// Generated by a workflow or automation.
    Workflow,
    /// Triggered from the TUI.
    Tui,
}

impl GitCommandOrigin {
    /// Stable string label used for persistence (e.g. `backend_detail`).
    pub fn label(self) -> &'static str {
        match self {
            Self::NativeTool => "native_tool",
            Self::BashTranslation => "bash_translation",
            Self::Workflow => "workflow",
            Self::Tui => "tui",
        }
    }
}
